### ISSUE TITLE
I want ice cream but I have gout

### ISSUE THREAD

**Issue by KeithCharlieTaylor** [kct2020/goutpal-com-skeleventy#72]
Page URL: https://gout-pal.com/gout-pal-forum/please-help-my-gout/i-want-ice-cream/

Page Title: I want ice cream but I have gout

Page Description: 9 Oct 2009 ... Tagged: Gout Dieter Discussions, Most Helpful Gout Forum, What foods are high in uric acid? This topic has 4 replies, 5 voices, and was last ...

## Additional context ##
Many gout sufferers ask, "Is ice cream bad for gout?" and have other concerns about ice cream & gout.

**Comment by kct2020** [comment]
Moved to new triage system
